// <auto-generated />
using System;
using MediFlow.Modules.Scheduling.Infastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace MediFlow.Modules.Scheduling.Migrations
{
    [DbContext(typeof(SchedulingDbContext))]
    partial class SchedulingDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("scheduling")
                .HasAnnotation("ProductVersion", "10.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("MediFlow.Modules.Scheduling.Domain.PractitionerAvailability.PractitionerAvailability", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("PractitionerId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.ToTable("PractitionerAvailabilities", "scheduling");
                });

            modelBuilder.Entity("MediFlow.Modules.Scheduling.Domain.SchedulingPractitionerReadModel", b =>
                {
                    b.Property<Guid>("PractitionerId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.HasKey("PractitionerId");

                    b.ToTable("SchedulingPractitionerReadModels", "scheduling");
                });

            modelBuilder.Entity("MediFlow.Modules.Scheduling.Domain.PractitionerAvailability.PractitionerAvailability", b =>
                {
                    b.OwnsMany("MediFlow.Modules.Scheduling.Domain.PractitionerAvailability.WeeklyAvailabilityRule", "Rules", b1 =>
                        {
                            b1.Property<Guid>("Id")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("uuid");

                            b1.Property<int>("DayOfWeek")
                                .HasColumnType("integer");

                            b1.Property<TimeOnly>("EndTime")
                                .HasColumnType("time without time zone");

                            b1.Property<Guid>("PractitionerAvailabilityId")
                                .HasColumnType("uuid");

                            b1.Property<TimeOnly>("StartTime")
                                .HasColumnType("time without time zone");

                            b1.HasKey("Id");

                            b1.HasIndex("PractitionerAvailabilityId");

                            b1.ToTable("WeeklyAvailabilityRules", "scheduling");

                            b1.WithOwner()
                                .HasForeignKey("PractitionerAvailabilityId");
                        });

                    b.Navigation("Rules");
                });
#pragma warning restore 612, 618
        }
    }
}
